/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedFlashcardsIndexRouteImport } from './routes/_authenticated/flashcards/index'
import { Route as AuthenticatedFlashcardsCreateRouteImport } from './routes/_authenticated/flashcards/create'
import { Route as AuthenticatedFlashcardsSetIdRouteImport } from './routes/_authenticated/flashcards/$setId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFlashcardsIndexRoute =
  AuthenticatedFlashcardsIndexRouteImport.update({
    id: '/flashcards/',
    path: '/flashcards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlashcardsCreateRoute =
  AuthenticatedFlashcardsCreateRouteImport.update({
    id: '/flashcards/create',
    path: '/flashcards/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlashcardsSetIdRoute =
  AuthenticatedFlashcardsSetIdRouteImport.update({
    id: '/flashcards/$setId',
    path: '/flashcards/$setId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/flashcards/$setId': typeof AuthenticatedFlashcardsSetIdRoute
  '/flashcards/create': typeof AuthenticatedFlashcardsCreateRoute
  '/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/flashcards/$setId': typeof AuthenticatedFlashcardsSetIdRoute
  '/flashcards/create': typeof AuthenticatedFlashcardsCreateRoute
  '/flashcards': typeof AuthenticatedFlashcardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/flashcards/$setId': typeof AuthenticatedFlashcardsSetIdRoute
  '/_authenticated/flashcards/create': typeof AuthenticatedFlashcardsCreateRoute
  '/_authenticated/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/flashcards/$setId'
    | '/flashcards/create'
    | '/flashcards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/flashcards/$setId'
    | '/flashcards/create'
    | '/flashcards'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/flashcards/$setId'
    | '/_authenticated/flashcards/create'
    | '/_authenticated/flashcards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/flashcards/': {
      id: '/_authenticated/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof AuthenticatedFlashcardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/create': {
      id: '/_authenticated/flashcards/create'
      path: '/flashcards/create'
      fullPath: '/flashcards/create'
      preLoaderRoute: typeof AuthenticatedFlashcardsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/$setId': {
      id: '/_authenticated/flashcards/$setId'
      path: '/flashcards/$setId'
      fullPath: '/flashcards/$setId'
      preLoaderRoute: typeof AuthenticatedFlashcardsSetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFlashcardsSetIdRoute: typeof AuthenticatedFlashcardsSetIdRoute
  AuthenticatedFlashcardsCreateRoute: typeof AuthenticatedFlashcardsCreateRoute
  AuthenticatedFlashcardsIndexRoute: typeof AuthenticatedFlashcardsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFlashcardsSetIdRoute: AuthenticatedFlashcardsSetIdRoute,
  AuthenticatedFlashcardsCreateRoute: AuthenticatedFlashcardsCreateRoute,
  AuthenticatedFlashcardsIndexRoute: AuthenticatedFlashcardsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
