/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedFlashcardsIndexRouteImport } from './routes/_authenticated/flashcards/index'
import { Route as AuthenticatedFlashcardsCreateRouteImport } from './routes/_authenticated/flashcards/create'
import { Route as AuthenticatedFlashcardsSetIdIndexRouteImport } from './routes/_authenticated/flashcards/$setId/index'
import { Route as AuthenticatedFlashcardsSetIdTestRouteImport } from './routes/_authenticated/flashcards/$setId/test'
import { Route as AuthenticatedFlashcardsSetIdFlashcardsRouteImport } from './routes/_authenticated/flashcards/$setId/flashcards'
import { Route as AuthenticatedFlashcardsSetIdEditRouteImport } from './routes/_authenticated/flashcards/$setId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFlashcardsIndexRoute =
  AuthenticatedFlashcardsIndexRouteImport.update({
    id: '/flashcards/',
    path: '/flashcards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlashcardsCreateRoute =
  AuthenticatedFlashcardsCreateRouteImport.update({
    id: '/flashcards/create',
    path: '/flashcards/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlashcardsSetIdIndexRoute =
  AuthenticatedFlashcardsSetIdIndexRouteImport.update({
    id: '/flashcards/$setId/',
    path: '/flashcards/$setId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlashcardsSetIdTestRoute =
  AuthenticatedFlashcardsSetIdTestRouteImport.update({
    id: '/flashcards/$setId/test',
    path: '/flashcards/$setId/test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlashcardsSetIdFlashcardsRoute =
  AuthenticatedFlashcardsSetIdFlashcardsRouteImport.update({
    id: '/flashcards/$setId/flashcards',
    path: '/flashcards/$setId/flashcards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlashcardsSetIdEditRoute =
  AuthenticatedFlashcardsSetIdEditRouteImport.update({
    id: '/flashcards/$setId/edit',
    path: '/flashcards/$setId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/flashcards/create': typeof AuthenticatedFlashcardsCreateRoute
  '/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/flashcards/$setId/edit': typeof AuthenticatedFlashcardsSetIdEditRoute
  '/flashcards/$setId/flashcards': typeof AuthenticatedFlashcardsSetIdFlashcardsRoute
  '/flashcards/$setId/test': typeof AuthenticatedFlashcardsSetIdTestRoute
  '/flashcards/$setId/': typeof AuthenticatedFlashcardsSetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/flashcards/create': typeof AuthenticatedFlashcardsCreateRoute
  '/flashcards': typeof AuthenticatedFlashcardsIndexRoute
  '/flashcards/$setId/edit': typeof AuthenticatedFlashcardsSetIdEditRoute
  '/flashcards/$setId/flashcards': typeof AuthenticatedFlashcardsSetIdFlashcardsRoute
  '/flashcards/$setId/test': typeof AuthenticatedFlashcardsSetIdTestRoute
  '/flashcards/$setId': typeof AuthenticatedFlashcardsSetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/flashcards/create': typeof AuthenticatedFlashcardsCreateRoute
  '/_authenticated/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/_authenticated/flashcards/$setId/edit': typeof AuthenticatedFlashcardsSetIdEditRoute
  '/_authenticated/flashcards/$setId/flashcards': typeof AuthenticatedFlashcardsSetIdFlashcardsRoute
  '/_authenticated/flashcards/$setId/test': typeof AuthenticatedFlashcardsSetIdTestRoute
  '/_authenticated/flashcards/$setId/': typeof AuthenticatedFlashcardsSetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/flashcards/create'
    | '/flashcards/'
    | '/flashcards/$setId/edit'
    | '/flashcards/$setId/flashcards'
    | '/flashcards/$setId/test'
    | '/flashcards/$setId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/flashcards/create'
    | '/flashcards'
    | '/flashcards/$setId/edit'
    | '/flashcards/$setId/flashcards'
    | '/flashcards/$setId/test'
    | '/flashcards/$setId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/flashcards/create'
    | '/_authenticated/flashcards/'
    | '/_authenticated/flashcards/$setId/edit'
    | '/_authenticated/flashcards/$setId/flashcards'
    | '/_authenticated/flashcards/$setId/test'
    | '/_authenticated/flashcards/$setId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/flashcards/': {
      id: '/_authenticated/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof AuthenticatedFlashcardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/create': {
      id: '/_authenticated/flashcards/create'
      path: '/flashcards/create'
      fullPath: '/flashcards/create'
      preLoaderRoute: typeof AuthenticatedFlashcardsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/$setId/': {
      id: '/_authenticated/flashcards/$setId/'
      path: '/flashcards/$setId'
      fullPath: '/flashcards/$setId/'
      preLoaderRoute: typeof AuthenticatedFlashcardsSetIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/$setId/test': {
      id: '/_authenticated/flashcards/$setId/test'
      path: '/flashcards/$setId/test'
      fullPath: '/flashcards/$setId/test'
      preLoaderRoute: typeof AuthenticatedFlashcardsSetIdTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/$setId/flashcards': {
      id: '/_authenticated/flashcards/$setId/flashcards'
      path: '/flashcards/$setId/flashcards'
      fullPath: '/flashcards/$setId/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsSetIdFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/$setId/edit': {
      id: '/_authenticated/flashcards/$setId/edit'
      path: '/flashcards/$setId/edit'
      fullPath: '/flashcards/$setId/edit'
      preLoaderRoute: typeof AuthenticatedFlashcardsSetIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFlashcardsCreateRoute: typeof AuthenticatedFlashcardsCreateRoute
  AuthenticatedFlashcardsIndexRoute: typeof AuthenticatedFlashcardsIndexRoute
  AuthenticatedFlashcardsSetIdEditRoute: typeof AuthenticatedFlashcardsSetIdEditRoute
  AuthenticatedFlashcardsSetIdFlashcardsRoute: typeof AuthenticatedFlashcardsSetIdFlashcardsRoute
  AuthenticatedFlashcardsSetIdTestRoute: typeof AuthenticatedFlashcardsSetIdTestRoute
  AuthenticatedFlashcardsSetIdIndexRoute: typeof AuthenticatedFlashcardsSetIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFlashcardsCreateRoute: AuthenticatedFlashcardsCreateRoute,
  AuthenticatedFlashcardsIndexRoute: AuthenticatedFlashcardsIndexRoute,
  AuthenticatedFlashcardsSetIdEditRoute: AuthenticatedFlashcardsSetIdEditRoute,
  AuthenticatedFlashcardsSetIdFlashcardsRoute:
    AuthenticatedFlashcardsSetIdFlashcardsRoute,
  AuthenticatedFlashcardsSetIdTestRoute: AuthenticatedFlashcardsSetIdTestRoute,
  AuthenticatedFlashcardsSetIdIndexRoute:
    AuthenticatedFlashcardsSetIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
